project_id = "txxadrpsnkotlavovnea"

[functions.enviar-orcamento]
verify_jwt = true

[functions.enviar-contrato]
verify_jwt = true

[functions.processar-contrato-docx]
verify_jwt = true

[functions.testar-email]
verify_jwt = true