// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txxadrpsnkotlavovnea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4eGFkcnBzbmtvdGxhdm92bmVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyODkyNjcsImV4cCI6MjA2Nzg2NTI2N30.n_S29PyKRVHuiv7qoNJYP82K7txGu8ogqfwzTKP7Uok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});